### ISSUE TITLE
FP2: Missing halium-7.1 branch on kernel repo

### ISSUE THREAD

**Issue by lnjX** [Halium/halium-devices#11]
In the manifest it says to clone the halium-7.1 branch (by using the hal remote) from the repo, but it's not existing
```xml
<project path="kernel/fairphone/msm8974" name="z3ntu/android_kernel_fairphone_msm8974" remote="hal" />
```

Please fix that @z3ntu. 😃

**Comment by jbruechert** [comment]
This manifest is probably only working with Halium 5.1. We should remove it from the 7.1 branch, and if it doesn't exist on the 5.1 branch, add it there.

**Comment by lnjX** [comment]
There is also no halium-5.1 branch, so that won't work either.

**Comment by jbruechert** [comment]
Uh ... then there's really something to fix

**Comment by z3ntu** [comment]
1. I never added that manifest myself ^^
2. I probably deleted them at a cleanup some time ago.
3. Why does the manifest point to my repo anyways?
4. I'll create the repos in the Halium organization and push the branches I still have backed up locally there.

**Comment by z3ntu** [comment]
See #16.
I have/will push(ed) both halium-7.1 from my repo and halium-5.1 from @peat-psuwit to the new Halium repositories. As mentioned in the PR, I am just pushing them to the repo and didn't test if they work.

**Comment by lnjX** [comment]
I didn't want to say it's your fault. I just want to make all manifests usable/working. Thanks for your pull request. 👍 😃
