### ISSUE TITLE
Unable to sync Halium due to bad ref in GIT repository

### ISSUE THREAD

**Issue by memiks** [Halium/halium-devices#159]
When I executed :
`repo sync -c -j 16`

I got this error:
 
> Syncing work tree:  51% (109/212)Traceback (most recent call last):
>   File "/media/data/memiks/halium/.repo/repo/main.py", line 547, in <module>
>     _Main(sys.argv[1:])
>   File "/media/data/memiks/halium/.repo/repo/main.py", line 522, in _Main
>     result = repo._Run(argv) or 0
>   File "/media/data/memiks/halium/.repo/repo/main.py", line 184, in _Run
>     result = cmd.Execute(copts, cargs)
>   File "/media/data/memiks/halium/.repo/repo/subcmds/sync.py", line 855, in Execute
>     project.Sync_LocalHalf(syncbuf, force_sync=opt.force_sync)
>   File "/media/data/memiks/halium/.repo/repo/project.py", line 1419, in Sync_LocalHalf
>     lost = self._revlist(not_rev(revid), HEAD)
>   File "/media/data/memiks/halium/.repo/repo/project.py", line 2619, in _revlist
>     return self.work_git.rev_list(*a, **kw)
>   File "/media/data/memiks/halium/.repo/repo/project.py", line 2819, in rev_list
>     (self._project.name, str(args), p.stderr))
> **error.GitError: Halium/halium-devices rev-list ('^3207e2e110f9b99fb099cf13b3ab2daf422a6033', 'HEAD', '--'): fatal: bad object HEAD**

Could you please help me how to fix this ?
BR,
Frederic.

**Comment by jbruechert** [comment]
Usually sync errors are related to earlier git crashes (sometimes for example SSL problems).
You could try deleting all halium-devices{.git,} folders in .repo and continue syncing.

**Comment by memiks** [comment]
Ok I did that many time...

I found a solution :
```
rm -rf halium-devices.git
rm -rf libhybris.git
git clone --bare https://github.com/Halium/halium-devices.git
git clone --bare https://github.com/Halium/libhybris.git
```

But now I had a new issue...

> 
> Syncing work tree:  97% (206/212)Traceback (most recent call last):
>   File "/media/data/memiks/halium/.repo/repo/main.py", line 547, in <module>
>     _Main(sys.argv[1:])
>   File "/media/data/memiks/halium/.repo/repo/main.py", line 522, in _Main
>     result = repo._Run(argv) or 0
>   File "/media/data/memiks/halium/.repo/repo/main.py", line 184, in _Run
>     result = cmd.Execute(copts, cargs)
>   File "/media/data/memiks/halium/.repo/repo/subcmds/sync.py", line 855, in Execute
>     project.Sync_LocalHalf(syncbuf, force_sync=opt.force_sync)
>   File "/media/data/memiks/halium/.repo/repo/project.py", line 1419, in Sync_LocalHalf
>     lost = self._revlist(not_rev(revid), HEAD)
>   File "/media/data/memiks/halium/.repo/repo/project.py", line 2619, in _revlist
>     return self.work_git.rev_list(*a, **kw)
>   File "/media/data/memiks/halium/.repo/repo/project.py", line 2819, in rev_list
>     (self._project.name, str(args), p.stderr))
> **UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 32: ordinal not in range(128)**

**Comment by jbruechert** [comment]
can you try syncing again after running `export LANG=en_US.UTF-8`, to make sure you are using utf8 and not ascii?

**Comment by memiks** [comment]
Ok...

So after :
```
export LANG=en_US.UTF-8
rm -rf .repo
repo init -u https://github.com/Halium/android -b halium-7.1 --depth=1
repo sync -c -j 16
```

I am able to sync the repo without issues...
_I will add a warning in the documentation_

Now I have other issues...

> [ 17% 3787/22071] Generated: (/media/data/memiks/halium/out/target/product/kenzo/android-info.txt)
> FAILED: /media/data/memiks/halium/out/target/product/kenzo/android-info.txt
> /bin/bash -c "(build/tools/check_radio_versions.py ) && (echo \"board=msm8952\" > /media/data/memiks/halium/out/target/product/kenzo/android-info.txt )"
>   File "build/tools/check_radio_versions.py", line 56
>     print "*** Error opening \"%s.sha1\"; can't verify %s" % (fn, key)
>                                                          ^
> SyntaxError: invalid syntax
> [ 17% 3787/22071] build /media/data/memiks/halium/out/target/product/kenzo/obj/ETC/sepolicy_intermediates/policy.conf
> ninja: build stopped: subcommand failed.
> make: *** [build/core/ninja.mk:152: ninja_wrapper] Error 1
> make: Leaving directory '/media/data/memiks/halium'

I will check...

Thanks !

**Comment by memiks** [comment]
OK Python3 --> Python2 issue...

Thanks for all help and the fish 👍

**Comment by kaushalsitapara** [comment]
so how did you fixed explain in detail,please

**Comment by SL-Pirate** [comment]
> OK Python3 --> Python2 issue...
> 
> Thanks for all help and the fish

How did you fix this?

**Comment by memiks** [comment]
Hi,

I created a Python2 Virtual Environment (venv) like explained here : [use-python2-7-in-venv-where-python3-is-default-python](https://stackoverflow.com/questions/54782163/use-python2-7-in-venv-where-python3-is-default-python)

`python27 -m virtualenv <path to venv>`

More explanaition about [python venv](https://python.land/virtual-environments/virtualenv)

BR

**Comment by SL-Pirate** [comment]
> Hi,
> 
> I created a Python2 Virtual Environment (venv) like explained here : [use-python2-7-in-venv-where-python3-is-default-python](https://stackoverflow.com/questions/54782163/use-python2-7-in-venv-where-python3-is-default-python)
> 
> `python27 -m virtualenv <path to venv>`
> 
> More explanaition about [python venv](https://python.land/virtual-environments/virtualenv)
> 
> BR

Thank you brother. But I found another solution ([script](https://review.lineageos.org/c/LineageOS/android_build/+/2981/2/tools/check_radio_versions.pyl).)

Thank you again for the quick reply
